/**
 * Tragofone theme — web source of truth (mirrors RN Theme.txt white-label section).
 * Only colors above the ❌ marker are defined here.
 */

(function initTragofoneTheme(global) {
  "use strict";

  // Gradient stop variables (white-label)
  var GRADIENT_1 = "#6533E2";
  var GRADIENT_2 = "#7349DE";
  var GRADIENT_3 = "#1F97EF";
  var GRADIENT_4 = "#57A1D7";
  var PRIMARY_COLOR = "#604D99";
  var CHAT_ICON_COLOR_RECIVER = "#614B98";
  var PRIMARY_DARK_COLOR = "#5834D3";

  var defaultTheme = {
    // full screen gradient
    fullScreenGradientLocations: [0.042, 0.334, 0.715, 0.9889],
    fullScreenGradientAngle: 223.54,
    // button gradient
    buttonGradientLocations: [0.002, 0.3, 0.97],
    buttonGradientAngle: 270,
    // navigation gradient
    navigationGradientLocations: [0.06, 0.35, 0.99, 1],
    navigationGradientAngle: 223.54,
    GRADIENT_1: GRADIENT_1,
    GRADIENT_2: GRADIENT_2,
    GRADIENT_3: GRADIENT_3,
    GRADIENT_4: GRADIENT_4,
    GRADIENT_COLORS: [GRADIENT_1, GRADIENT_2, GRADIENT_3, GRADIENT_4],
    BUTTON_GRADIENT_COLOR: [GRADIENT_1, GRADIENT_2, GRADIENT_3],
    NAVIGATION_GRADIENT_COLOR: [GRADIENT_1, GRADIENT_2, GRADIENT_3, GRADIENT_4],
    PRIMARY_COLOR: PRIMARY_COLOR,
    PRIMARY_THEME_TEXT: PRIMARY_COLOR,
    PRIMARY_BG: PRIMARY_COLOR,
    PRIMARY_ICON: PRIMARY_COLOR,
    CHAT_ICON_COLOR_RECIVER: CHAT_ICON_COLOR_RECIVER,
    AUDIO_PLAYER_BUTTON_COLOR: CHAT_ICON_COLOR_RECIVER,
    SECONDARY_COLOR_PRESENCE: CHAT_ICON_COLOR_RECIVER,
    CONTACT_AVATAR_PHONE_USER: CHAT_ICON_COLOR_RECIVER,
    CONTACT_AVATAR_REMOTE_BG: CHAT_ICON_COLOR_RECIVER,
    CONTACT_AVATAR_REMOTE_USER: CHAT_ICON_COLOR_RECIVER,
    CONTACT_AVATAR_PHONE_BG: CHAT_ICON_COLOR_RECIVER,
    IMG_UPLOAD_ICON: CHAT_ICON_COLOR_RECIVER,
    LOTTIE_COLOR: CHAT_ICON_COLOR_RECIVER,
    INPUT_BORDER_COLOR: PRIMARY_COLOR,
    CALL_ICON_ACTIVE: PRIMARY_COLOR,
    CHAT_RECIVER_ICON_COLOR: CHAT_ICON_COLOR_RECIVER,
    CHAT_RECIVER_AUDIO_PLAY_ICON_COLOR: CHAT_ICON_COLOR_RECIVER,
    CHAT_SENDER_AUDIO_PLAY_ICON_COLOR: CHAT_ICON_COLOR_RECIVER,
    LOADER_COLOR: PRIMARY_COLOR,
    FLASH_ICON: "#579CD3",
    POLICY_TEXT_COLOR: GRADIENT_4,
    BUTTON_COLOR_BLUE: GRADIENT_4,
    SEEKBAR_FEEL_CORLOR: GRADIENT_4,
    CONTACT_AVATAR_PHONE_BG_NEW: GRADIENT_4,
    WEBVIEW_BG: "#534DC2",
    PRIMARY_DARK_COLOR: PRIMARY_DARK_COLOR,
    PRIMARY_DARK_ICON: PRIMARY_DARK_COLOR,
    PRIMARY_DARK_COLOR_50: PRIMARY_DARK_COLOR + "80",
    GET_STARTED_DISCIMAR_TEXT: "#ffffff",
    SECONDARY_COLOR: "#a5a5a5",
    PERMISSION_GRAY_BACKGROUND: "#d8d8d8",
    SEARCH_BAR_TEXT_COLOR: "#ffffff",
    SEARCH_BAR_COLOR: "rgba(255, 255, 255, 0.4)",
    SEARCH_BAR_ICON_COLOR: "#ffffff",
    SEARCH_BAR_TINT_COLOR: "#ffffff",
    DROPDOWN_BAR_COLOR: "rgba(255, 255, 255, 0.4)",
    APPLOCK_GREY_LIGHT: "#a5a5a5",
    TEXT_COLOR: "#000000",
    MODAL_TITLE: "#000000",
    CALL_ICON_BG: "#ffffff",
    FAV_SELECTED_COLOR: "#EDCB30",
    HEADER_TINT_COLOR_LIGHT: "#ffffff",
    CONTACT_ICONS: "#000000",
    LED_AWAY_COLOR: "#FCA51C",
    CHAT_TEXT_SENDER_COLOR: "#474747",
    ICON_COLOR: "#ffffff",
    SEARCH_BAR_ROASTER: "#9494944D",
    HINT_TEXT_Y: "#474747",
    CALL_TEXT_COLOR: "#ffffff",
    CALL_ICON_ACTIVE_BG: "#ffffff",
    DIALPAD_CONTACT_TEXT_COLOR: "#ffffff",
    CONNECT_SCREEN_BG: "#ffffff0d",
    PRIMARY_WHITE_TEXT: "#ffffff",
    LANGUAGE_ICON_COLOR: "#FF5757",
    CANCEL_BUTTON_COLOR: "#05AAFF",
    HEADER_TINT_COLOR: "#ffffff",
    HEADER_TEXT_COLOR: "#ffffff",
    HEADER_BACKGROUND_COLOR: "transparent",
    LOG_BUTTON_BACKGROUND: "#FFFFFF1C",
    CHAT_RECIVER_BUBBLE_BACKGROUND: "#E0E0E0",
    CHAT_RECIVER_BUBBLE_TEXTCOLOR: "#000000",
    CHAT_RECIVER_BUBBLE_TEXT_LINK_COLOR: "#6E97F5",
    CHAT_RECIVER_MESSAGE_TIME_TEXT_COLOR: "#474747",
    CHAT_RECIVER_ICON_BACKGROUND: "#D2D2D2",
    CHAT_SENDER_ICON_COLOR_LIGHT_THEME: "#006BE0",
    CHAT_SENDER_BUBBLE_BACKGROUND: "#C4E5FF",
    CHAT_SENDER_BUBBLE_TEXTCOLOR: "#000000",
    CHAT_SENDER_BUBBLE_TEXT_LINK_COLOR: "#6E97F5",
    CHAT_SENDER_MESSAGE_TIME_TEXT_COLOR: "#474747",
    CHAT_SENDER_ICON_COLOR: "#006BE0",
    CHAT_SENDER_ICON_BACKGROUND: "#ABDAFF",
    SMS_RECIVER_BUBBLE_BACKGROUND: "#E0E0E0",
    SMS_RECIVER_BUBBLE_TEXTCOLOR: "#000000",
    SMS_RECIVER_BUBBLE_TEXT_LINK_COLOR: "#6E97F5",
    SMS_RECIVER_AUDIO_TIME_TEXT_COLOR: "#474747",
    SMS_SENDER_BUBBLE_BACKGROUND: "#C4E5FF",
    SMS_SENDER_BUBBLE_TEXTCOLOR: "#000000",
    SMS_SENDER_BUBBLE_TEXT_LINK_COLOR: "#6E97F5",
    SMS_SENDER_AUDIO_TIME_TEXT_COLOR: "#474747",
    CHAT_RECEIVED: "#006BE0",
  };

  /** Keys eligible for runtime CSS injection (scalar colors only). */
  var WHITE_LABEL_CSS_KEYS = Object.keys(defaultTheme).filter(function (key) {
    var value = defaultTheme[key];
    return (
      typeof value === "string" &&
      (value.charAt(0) === "#" || value.indexOf("rgba") === 0 || value === "transparent")
    );
  });

  global.TRAGO_GRADIENT_1 = GRADIENT_1;
  global.TRAGO_GRADIENT_2 = GRADIENT_2;
  global.TRAGO_GRADIENT_3 = GRADIENT_3;
  global.TRAGO_GRADIENT_4 = GRADIENT_4;
  global.TRAGO_DEFAULT_THEME = defaultTheme;
  global.TRAGO_WHITE_LABEL_CSS_KEYS = WHITE_LABEL_CSS_KEYS;
})(window);
